// deno-lint-ignore-file

// This file is automatically generated by deno_bindgen.
// Do not edit this file directly.

let symbols: any;

import { dlopen, FetchOptions } from "@denosaurs/plug";
import denoJson from "../../deno.json" with { type: "json" };

if (!("version" in denoJson) || typeof denoJson.version !== "string") {
  throw new Error("specify 'version' field in deno json");
}

const baseURL =
  `https://github.com/TomokiMiyauci/file-system-access/releases/download/${denoJson.version}`;

const options: FetchOptions = {
  name: "file_dialog",
  url: baseURL,
  suffixes: {
    darwin: {
      aarch64: "_aarch64-apple-darwin",
      x86_64: "_x86_64-apple-darwin",
    },
  },
};

export async function load() {
  const { symbols: symbols_ } = await dlopen(options, {
    __Dialog_new: {
      parameters: [],
      result: "pointer",
      nonblocking: false,
    },
    __Dialog_pick_file: {
      parameters: [
        "pointer",
      ],
      result: "pointer",
      nonblocking: false,
    },
    __Dialog_pick_files: {
      parameters: [
        "pointer",
      ],
      result: "pointer",
      nonblocking: false,
    },
    __Dialog_pick_directory: {
      parameters: [
        "pointer",
      ],
      result: "pointer",
      nonblocking: false,
    },
    __Dialog_set_directory: {
      parameters: [
        "pointer",
        "buffer",
        "usize",
      ],
      result: "pointer",
      nonblocking: false,
    },
    __Dialog_add_filter: {
      parameters: [
        "pointer",
        "buffer",
        "usize",
      ],
      result: "pointer",
      nonblocking: false,
    },
    __Dialog_dealloc: {
      parameters: [
        "pointer",
      ],
      result: "void",
      nonblocking: false,
    },
  });

  symbols = symbols_;
}

function __Dialog_new(): Dialog {
  const ret = symbols.__Dialog_new();
  return Dialog.__constructor(ret);
}

function __Dialog_pick_file(
  arg0: Deno.PointerObject | null,
): Deno.PointerObject | null {
  return symbols.__Dialog_pick_file(
    arg0,
  );
}

function __Dialog_pick_files(
  arg0: Deno.PointerObject | null,
): Deno.PointerObject | null {
  return symbols.__Dialog_pick_files(
    arg0,
  );
}

function __Dialog_pick_directory(
  arg0: Deno.PointerObject | null,
): Deno.PointerObject | null {
  return symbols.__Dialog_pick_directory(
    arg0,
  );
}

function __Dialog_set_directory(
  arg0: Deno.PointerObject | null,
  arg1: Uint8Array,
): Dialog {
  const ret = symbols.__Dialog_set_directory(
    arg0,
    arg1,
    arg1.byteLength,
  );
  return Dialog.__constructor(ret);
}

function __Dialog_add_filter(
  arg0: Deno.PointerObject | null,
  arg1: Uint8Array,
): Dialog {
  const ret = symbols.__Dialog_add_filter(
    arg0,
    arg1,
    arg1.byteLength,
  );
  return Dialog.__constructor(ret);
}

function __Dialog_dealloc(
  arg0: Deno.PointerObject | null,
): void {
  return symbols.__Dialog_dealloc(
    arg0,
  );
}

export class Dialog {
  ptr: Deno.PointerObject | null = null;

  static __constructor(ptr: Deno.PointerObject | null) {
    const self = Object.create(Dialog.prototype);
    self.ptr = ptr;
    return self;
  }

  [Symbol.dispose]() {
    this.dealloc();
    this.ptr = null;
  }

  constructor() {
    return __Dialog_new();
  }

  pick_file(): Deno.PointerObject | null {
    return __Dialog_pick_file(
      this.ptr,
    );
  }

  pick_files(): Deno.PointerObject | null {
    return __Dialog_pick_files(
      this.ptr,
    );
  }

  pick_directory(): Deno.PointerObject | null {
    return __Dialog_pick_directory(
      this.ptr,
    );
  }

  set_directory(arg0: Uint8Array): Dialog {
    return __Dialog_set_directory(
      this.ptr,
      arg0,
      arg0.byteLength,
    );
  }

  add_filter(arg0: Uint8Array): Dialog {
    return __Dialog_add_filter(
      this.ptr,
      arg0,
      arg0.byteLength,
    );
  }

  dealloc(): void {
    return __Dialog_dealloc(
      this.ptr,
    );
  }
}
